# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and release project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - run: |
        git fetch --prune --unshallow --tags
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew check -Pbintray_user=dummy -Pbintray_api_key=dummy
    - name: Release artifact
      if: ${{ github.event_name == 'push' }}
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      run: |
        ./gradlew final -Pbintray_user="$BINTRAY_USER" -Pbintray_api_key="$BINTRAY_API_KEY"
